-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm8BgbUeGiZJ0lg9a
6omcVf/HjQLrpAZLYsPPqxeZdrugCgYIKoZIzj0DAQehRANCAASYdsR8Nk9HxBAB
knDOxLA8PLRO5YGQAQ0wfvQx5KmZIBVZPTWjpudGFzrrFKWI6XN/mWQYnZR4CKst
njDSUq52
-----END PRIVATE KEY-----