# Generated by Django 5.2.10 on 2026-02-19 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('total_online_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('address_text', models.TextField(blank=True)),
                ('police_record', models.ImageField(blank=True, null=True, upload_to='police_records/')),
                ('proof_of_address', models.ImageField(blank=True, null=True, upload_to='address_records/')),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('total_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('wrecker', 'Wrecker'), ('removal_truck', 'Removal Truck')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driving_license_front', models.ImageField(upload_to='licenses/')),
                ('driving_license_back', models.ImageField(upload_to='licenses/')),
                ('national_id_front', models.ImageField(blank=True, null=True, upload_to='national_ids/')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='national_ids/')),
                ('vehicle_registration', models.ImageField(blank=True, null=True, upload_to='reg_documents/')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='driver.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='driver.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
