# Generated by Django 5.2.10 on 2026-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
    ]
