# Generated by Django 6.0.2 on 2026-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='d_type',
            field=models.CharField(choices=[('general', 'general'), ('gas', 'gas')], default='general', max_length=20),
        ),
    ]
