# Generated by Django 5.2.10 on 2026-02-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_truck'),
        ('driver', '0003_driver_d_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='assign_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck', to='company.truck'),
        ),
    ]
