# Generated by Django 5.2.10 on 2026-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_assign_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
