# Generated by Django 5.2.10 on 2026-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driver_driver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='availability_status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
