# Generated by Django 5.2.10 on 2026-03-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_driver_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
