# Generated by Django 5.2.10 on 2026-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_drivertransaction_withdrawrequest_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
