# Generated by Django 5.2.10 on 2026-02-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('company', 'Company'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
