# Generated by Django 5.2.10 on 2026-02-20 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_type', models.CharField(choices=[('ecommerce', 'E-commerce / Shiping Company'), ('gas_company', 'Gas Company')], default='ecommerce', max_length=30)),
                ('business_name', models.CharField(db_index=True, max_length=150)),
                ('business_address', models.TextField()),
                ('business_license', models.FileField(blank=True, null=True, upload_to='business_licenses/')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['business_type', 'is_verified'], name='company_com_busines_e076cf_idx'), models.Index(fields=['business_name'], name='company_com_busines_be3806_idx')],
            },
            bases=('accounts.user',),
        ),
    ]
