# Generated by Django 5.2.10 on 2026-02-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
