# Generated by Django 5.2.10 on 2026-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='operating_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
