# Generated by Django 5.2.10 on 2026-03-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_truck_operating_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='operating_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.zone'),
        ),
    ]
