# Generated by Django 5.2.10 on 2026-02-18 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('address_text', models.TextField()),
                ('parish', models.CharField(choices=[('kingston', 'Kingston'), ('st_andrew', 'St. Andrew'), ('st_catherine', 'St. Catherine'), ('clarendon', 'Clarendon'), ('manchester', 'Manchester'), ('st_elizabeth', 'St. Elizabeth'), ('westmoreland', 'Westmoreland'), ('hanover', 'Hanover'), ('st_james', 'St. James'), ('trelawny', 'Trelawny'), ('st_ann', 'St. Ann'), ('st_mary', 'St. Mary'), ('portland', 'Portland'), ('st_thomas', 'St. Thomas')], max_length=30)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_type_required', models.CharField(choices=[('bike', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('delivery_date', models.DateField()),
                ('delivery_time_window_start', models.TimeField(blank=True, null=True)),
                ('delivery_time_window_end', models.TimeField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='JMD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('confirmation_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='driver.driver')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_from', to='order.address')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_to', to='order.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('sensitivity_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('high_value', 'High Value')], max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='order_order_custome_d581fb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver', 'status'], name='order_order_driver__85580a_idx'),
        ),
    ]
