# Generated by Django 5.2.10 on 2026-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
