# Generated by Django 5.2.10 on 2026-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delivery_price_breakdown_delivery_service_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('van', 'Van'), ('wrecker', 'Wrecker'), ('removal_truck', 'Truck')], max_length=20, null=True),
        ),
    ]
