# Generated by Django 5.2.10 on 2026-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_delivery_pickup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
