# Generated by Django 5.2.10 on 2026-02-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_delivery_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='service_type',
            field=models.CharField(choices=[('pickup_delivery', 'Pickup'), ('wrecker', 'Wrecker'), ('removal_truck', 'Removal'), ('cooking_gas', 'Gas'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van')], max_length=30),
        ),
    ]
