# Generated by Django 5.2.10 on 2026-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_delivery_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver_last_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_last_heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_last_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimat_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
