# Generated by Django 5.2.10 on 2026-02-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_delivery_driver_last_accuracy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='estimat_arrival_time',
            new_name='estimate_arrival_time',
        ),
    ]
