# Generated by Django 5.2.10 on 2026-02-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_estimat_arrival_time_delivery_estimate_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='driver_last_accuracy',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='driver_last_heading',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='driver_last_speed',
        ),
    ]
