# Generated by Django 5.2.10 on 2026-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_delivery_driver_last_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='estimate_arrival_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
